config/routes.rb
Rails.application.routes.draw do
  resources :coins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :subscribers
  root 'static_pages#index'
  
  post '/', to:  'subscribers#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coin.rb
class Coin < ApplicationRecord
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  before_save { email.downcase! }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {minimum: 1, maximum: 255}, format: { with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :set_coin, only: [:show, :edit, :update, :destroy]

  # GET /coins
  # GET /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1
  # GET /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins
  # POST /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to @coin, notice: 'Coin was successfully created.' }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1
  # PATCH/PUT /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to @coin, notice: 'Coin was successfully updated.' }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1
  # DELETE /coins/1.json
  def destroy
    @coin.destroy
    respond_to do |format|
      format.html { redirect_to coins_url, notice: 'Coin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coin_params
      params.require(:coin).permit(:name, :ranking, :speed, :team, :community, :development, :adoption, :reputation, :wallet, :github, :wiki, :subreddit)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def index
    @subscriber = Subscriber.new 
  end 
  

end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  def create 
    @subscriber = Subscriber.new(subscriber_params)
    if @subscriber.save 
      cookies[:saved_subscriber] = true
      redirect_to root_path, notice: "EMAIL SUBSCRIBED!"
      cookies.delete :saved_subscriber
    else 
      redirect_to root_path, notice: "SUBMISSION ERROR"
    end 
  end
  
  private   
    def subscriber_params
      params.require(:subscriber).permit(:email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/coins/_form.html.erb
<%= form_with(model: coin, local: true) do |form| %>
  <% if coin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
      <% coin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :ranking %>
    <%= form.text_field :ranking %>
  </div>

  <div class="field">
    <%= form.label :speed %>
    <%= form.text_field :speed %>
  </div>

  <div class="field">
    <%= form.label :team %>
    <%= form.text_field :team %>
  </div>

  <div class="field">
    <%= form.label :community %>
    <%= form.text_field :community %>
  </div>

  <div class="field">
    <%= form.label :development %>
    <%= form.text_field :development %>
  </div>

  <div class="field">
    <%= form.label :adoption %>
    <%= form.text_field :adoption %>
  </div>

  <div class="field">
    <%= form.label :reputation %>
    <%= form.text_field :reputation %>
  </div>

  <div class="field">
    <%= form.label :wallet %>
    <%= form.text_field :wallet %>
  </div>

  <div class="field">
    <%= form.label :github %>
    <%= form.text_field :github %>
  </div>

  <div class="field">
    <%= form.label :wiki %>
    <%= form.text_field :wiki %>
  </div>

  <div class="field">
    <%= form.label :subreddit %>
    <%= form.text_field :subreddit %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/coins/edit.html.erb
<h1>Editing Coin</h1>

<%= render 'form', coin: @coin %>

<%= link_to 'Show', @coin %> |
<%= link_to 'Back', coins_path %>

app/views/coins/index.html.erb
<div class="container-coins">
<p id="notice"><%= notice %></p>

<table>
  <tbody>
    <tr class="coin-element">
      <td>#</td>
      <td>NAME</td>
      <td>SCORE</td>
    </tr>
    <% @coins.each do |coin| %>
      <tr class="coin-element">
        <td>0</td>
        <td><%= coin.name %></td>
        <td><%= coin.ranking %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to new_coin_path do %>
  <button class="submit-button">NEW COIN</button>
<% end %>
</div>

app/views/coins/new.html.erb
<h1>New Coin</h1>

<%= render 'form', coin: @coin %>

<%= link_to 'Back', coins_path %>

app/views/coins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @coin.name %>
</p>

<p>
  <strong>Ranking:</strong>
  <%= @coin.ranking %>
</p>

<p>
  <strong>Speed:</strong>
  <%= @coin.speed %>
</p>

<p>
  <strong>Team:</strong>
  <%= @coin.team %>
</p>

<p>
  <strong>Community:</strong>
  <%= @coin.community %>
</p>

<p>
  <strong>Development:</strong>
  <%= @coin.development %>
</p>

<p>
  <strong>Adoption:</strong>
  <%= @coin.adoption %>
</p>

<p>
  <strong>Reputation:</strong>
  <%= @coin.reputation %>
</p>

<p>
  <strong>Wallet:</strong>
  <%= @coin.wallet %>
</p>

<p>
  <strong>Github:</strong>
  <%= @coin.github %>
</p>

<p>
  <strong>Wiki:</strong>
  <%= @coin.wiki %>
</p>

<p>
  <strong>Subreddit:</strong>
  <%= @coin.subreddit %>
</p>

<%= link_to 'Edit', edit_coin_path(@coin) %> |
<%= link_to 'Back', coins_path %>

app/views/layouts/_footer.html.erb
<footer>

  <div class="footer-container">
      <div class="footer-column"><ul>
    <li>RESOURCES</li>
    <li>GUIDES</li>
    <li>EXCHANGE RANKINGS</li>
    <li>COIN RANKINGS</li>
  </ul></div>
  <div class="footer-column"><ul>
    <li>COMPANY</li>
        <li>ABOUT</li>
        <li>CONTACT</li>
        <li>SITEMAP</li>
        <li><a href="https://docs.google.com/forms/d/e/1FAIpQLSfA2kYHSJQLlwhpIqGwwCYaqIYYiZ7dTuPGKeOTEnVtYhSvHQ/viewform">FEEDBACK</a></li>   
  </ul>
</div>
  <div class="footer-column">  
    <a href="https://www.buymeacoffee.com/cryptoquery"><i class="fas fa-coffee"></i></a>
    <a href="https://twitter.com/CryptoQuery_"><i class="fab fa-twitter"></i></a>
    <div class="copyright-text">© <a href="/">Cryptoquery</a></div>
</div>
</div>

</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="header-container">
    <%= link_to root_path do %>
    <%= image_tag("cq-logo.svg", alt: "Cryptoquery", class: "cq-logo") %>
    <% end %> 
    <nav>
      <li id="about-li"><a href="/">GUIDES</a></li>
      <li id="contact-li"><a href="/">COINS</a></li>
      <li id="contact-li"><a href="/">EXCHANGES</a></li>
      <i aria-label="Menu" id="menu" class="fas fa-bars"></i>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Google Tag Manager -->
  <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
  new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
  j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
  'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
  })(window,document,'script','dataLayer','GTM-5KNCR53');</script>
  <!-- End Google Tag Manager -->
  
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Cryptoquery | Currency and Exchange Ratings</title>
  <%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                                          'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">


<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans:400,700" />
<%= favicon_link_tag asset_path('favicon.png') %>
</head>
<body>
  <!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5KNCR53"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

  <% if !current_page?(root_path) %>
  <%= render 'layouts/header' %>
  <%= yield %>
  <%= render 'layouts/footer' %>
  <% else %>
  <%= yield %>
  <% end %>

</body>
</html>

app/views/static_pages/index.html.erb
<div class="container-subscriber">
<%= image_tag("cq-logo.svg", alt: "Cryptoquery", class: "cq-logo") %>

<div class="cq-text">COMING SOON.</div>
<% if notice %>
  <div class="notice"><%= notice %></div>
<% end %>
<h3 class="signup-text">REGISTER FOR UPDATES</h3>
<div id="form-container">
<i class="far fa-envelope"></i>
<%= form_for @subscriber, :html => {class: "signup-form"} do |f| %>
  <%= f.email_field :email, placeholder: "EMAIL", class: "email-field", required: true %>
  <%= f.submit "GET UPDATES", class: "submit-button" %>
<% end %>
</div>
</div>